blank_issues_enabled: false
contact_links:
  - name: Testanleitung lesen
    url: https://github.com/LeonelDevX/RecCraft-Beta-Tester/blob/main/docs/TESTEN.md
    about: Bitte vor dem Melden die Testanleitung lesen.
