blank_issues_enabled: false
contact_links:
  - name: Read the Beta Testing Guide
    url: https://github.com/LeonelDevX/RecCraft-Beta-Tester/blob/main/docs/TESTEN.md
    about: Please read the testing guide before submitting a report.
